# Getting image from docker hub
from httpd

RUN apt-get update && apt-get install -y --no-install-recommends python3-dev python3-setuptools python3-wheel python3-pip 
ENV PYTHONPATH "${PYTHONPATH}:/usr/bin/python3"
RUN pip install onnxruntime==1.14.1
