# This workflow will install Python dependencies and run a basic test to ensure
# that the Cloud/Azure CLI is still working
name: Test Azure CLI

on:
  push:
    branches: ["main"]
    paths:
      - src/mlagility/cli/cloud/**
  pull_request:
    branches: ["main"]
    paths:
      - src/mlagility/cli/cloud/**

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: mla
          python-version: 3.8
      - name: Install dependencies
        shell: bash -el {0}
        run: |
          python -m pip install --upgrade pip
          pip install -r src/mlagility/cli/cloud/requirements.txt
      - name: Run tests
        shell: bash -el {0}
        run: |
          python src/mlagility/cli/cloud/control.py create setup selftest info stop --cluster --name github_test_azure --size 2 --hardware cpu-small
          python src/mlagility/cli/cloud/control.py start run delete --cluster --name github_test_azure --size 2 --hardware cpu-small --input-files models/selftest/*.py
